/*

 CAMMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\fl4v10\Downloads\gbtd\saves\camTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define CamMapWidth 20
#define CamMapHeight 18
#define CamMapBank 0

extern unsigned char CamMap[];

/* End of CAMMAP.H */
