/*

 SETA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define setaBank 0

/* Super Gameboy palette 0 */
#define setaSGBPal0c0 6076
#define setaSGBPal0c1 8935
#define setaSGBPal0c2 6596
#define setaSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define setaSGBPal1c0 6076
#define setaSGBPal1c1 8935
#define setaSGBPal1c2 6596
#define setaSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define setaSGBPal2c0 6076
#define setaSGBPal2c1 8935
#define setaSGBPal2c2 6596
#define setaSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define setaSGBPal3c0 6076
#define setaSGBPal3c1 8935
#define setaSGBPal3c2 6596
#define setaSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define setaCGBPal0c0 6076
#define setaCGBPal0c1 26425
#define setaCGBPal0c2 0
#define setaCGBPal0c3 14798

/* Gameboy Color palette 1 */
#define setaCGBPal1c0 6076
#define setaCGBPal1c1 8935
#define setaCGBPal1c2 6596
#define setaCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define setaCGBPal2c0 6076
#define setaCGBPal2c1 8935
#define setaCGBPal2c2 6596
#define setaCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define setaCGBPal3c0 6076
#define setaCGBPal3c1 8935
#define setaCGBPal3c2 6596
#define setaCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define setaCGBPal4c0 6076
#define setaCGBPal4c1 8935
#define setaCGBPal4c2 6596
#define setaCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define setaCGBPal5c0 6076
#define setaCGBPal5c1 8935
#define setaCGBPal5c2 6596
#define setaCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define setaCGBPal6c0 6076
#define setaCGBPal6c1 8935
#define setaCGBPal6c2 6596
#define setaCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define setaCGBPal7c0 6076
#define setaCGBPal7c1 8935
#define setaCGBPal7c2 6596
#define setaCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char setaCGB[];
/* Start of tile array. */
extern unsigned char seta[];

/* End of SETA.H */
