/*

 SETA.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char setaCGB[] =
{
  0x00
};
/* Start of tile array. */
unsigned char seta[] =
{
  0x00,0x18,0x10,0x2F,0x3F,0x40,0x7F,0xC0,
  0x3F,0x6F,0x10,0x3F,0x00,0x18,0x00,0x00
};

/* End of SETA.C */
