/*

 TUTORIAL_FNAF.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\fl4v10\Downloads\gbtd\saves\fonte.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tutorialmapWidth 20
#define tutorialmapHeight 18
#define tutorialmapBank 0

extern unsigned char tutorialmap[];

/* End of TUTORIAL_FNAF.H */
